### ISSUE TITLE
Unique PDFs

### ISSUE THREAD

**Issue by 1stdevfriend** [simplesolutiondev/java-export-pdf#1]
```java
String pdfFileName = "D:\\SimpleSolution\\order.pdf";
```
can be changed to a unique name/number from object description.

**Comment by simplesolutiondev** [comment]
Yes, you can change to a unique name like this. 
```

import java.util.UUID;

...

String pdfFileName = "D:\\SimpleSolution\\" + UUID.randomUUID().toString() + ".pdf";
```

**Comment by 1stdevfriend** [comment]
I'd still suggest to have description in the title of the pdf and a handler for protecting overwriting. This way you can store all the PDFs at one place without losing any receipt. 😀

**Comment by simplesolutiondev** [comment]
Thank you
